### ISSUE TITLE
Typo in "cmake_parse_arguments(_PCH "FORCEINCLUDE" "SOURCE_CXX;SOURCE_C" "" ${ARGN})"

### ISSUE THREAD

**Issue by MonkeyDied** [larsch/cmake-precompiled-header#5]
Line 79 reads
    cmake_parse_arguments(_PCH "FORCEINCLUDE" "SOURCE_CXX:SOURCE_C" "" ${ARGN})
Is it a typo that  "SOURCE_CXX:SOURCE_C" should be  "SOURCE_CXX;SOURCE_C"? 
Currently it is a colon ":" but it seems that it should be a semicolon “;”

**Comment by janosvitok** [comment]
fixed by commit d473a8510

**Comment by larsch** [comment]
Agreed, was fixed.
